USE [master]
GO

/****** Object:  Database [DbEventful]    Script Date: 08/02/2023 20:51:22 ******/
CREATE DATABASE [DbEventful]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DbEventful', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DbEventful.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DbEventful_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DbEventful_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbEventful].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DbEventful] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DbEventful] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DbEventful] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DbEventful] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DbEventful] SET ARITHABORT OFF 
GO

ALTER DATABASE [DbEventful] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DbEventful] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DbEventful] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DbEventful] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DbEventful] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DbEventful] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DbEventful] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DbEventful] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DbEventful] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DbEventful] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DbEventful] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DbEventful] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DbEventful] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DbEventful] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DbEventful] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DbEventful] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DbEventful] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DbEventful] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DbEventful] SET  MULTI_USER 
GO

ALTER DATABASE [DbEventful] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DbEventful] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DbEventful] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DbEventful] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DbEventful] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DbEventful] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DbEventful] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DbEventful] SET  READ_WRITE 
GO


USE [DbEventful]
GO

/****** Object:  Table [dbo].[Event]    Script Date: 08/02/2023 20:52:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Event](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[Description] [varchar](max) NOT NULL,
	[Banner] [varchar](max) NOT NULL,
	[Datetime] [datetime] NOT NULL,
	[Cep] [char](8) NOT NULL,
	[City] [varchar](50) NOT NULL,
	[Uf] [char](2) NOT NULL,
	[Address] [varchar](100) NOT NULL,
	[Number] [varchar](5) NOT NULL,
	[Active] [bit] NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[ChangeDate] [datetime] NULL,
	[CreationUser] [int] NOT NULL,
	[ChangeUser] [int] NULL,
 CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [DbEventful]
GO

/****** Object:  Table [dbo].[User]    Script Date: 08/02/2023 20:53:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](20) NOT NULL,
	[LastName] [varchar](20) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[Cpf] [char](11) NOT NULL,
	[Birthdate] [datetime] NOT NULL,
	[Genre] [tinyint] NOT NULL,
	[AcceptedTerms] [bit] NOT NULL,
	[Active] [bit] NULL,
	[CreationDate] [datetime] NULL,
	[ChangeDate] [datetime] NULL,
	[CreationUser] [int] NULL,
	[ChangeUser] [int] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

